server:
  port: 9010
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos/
    routeAuth:
      enable: true
      username: nacos
      password: nacos
    routes:
      - name: 字典服务
        serviceName: dict-service
        location: /v2/api-docs?group=dict
        servicePath: /dict-service
